import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { after, test } from "node:test";

const execFileAsync = promisify(execFile);

const SOURCE_TAGS = new Set([
  "README",
  "Git",
  "Graphify",
  "Task Hub",
  "SR",
  "Manual",
  "Generated",
  "none",
]);

const MEMORY_FIELDS = [
  "purpose",
  "status",
  "git",
  "readme",
  "sdd",
  "deployment",
  "nextStep",
];

const tempDirs = [];

after(async () => {
  await Promise.all(tempDirs.map((directory) => rm(directory, { recursive: true, force: true })));
});

async function loadMemory() {
  const module = await import("../server/project-memory.mjs");
  return module.generateProjectMemory;
}

async function createTempDir(prefix) {
  const directory = await mkdtemp(path.join(os.tmpdir(), prefix));
  tempDirs.push(directory);
  return directory;
}

async function createProjectWithReadmeAndGit() {
  const workspacePath = await createTempDir("project-memory-known-");
  await writeFile(
    path.join(workspacePath, "README.md"),
    "# Demo App\n\nThis project tracks fish inventory for store ops.\n",
  );
  await execFileAsync("git", ["init"], { cwd: workspacePath });
  await execFileAsync("git", ["config", "user.email", "test@example.com"], { cwd: workspacePath });
  await execFileAsync("git", ["config", "user.name", "Test User"], { cwd: workspacePath });
  await execFileAsync("git", ["add", "README.md"], { cwd: workspacePath });
  await execFileAsync("git", ["commit", "-m", "initial"], { cwd: workspacePath });
  return workspacePath;
}

function assertFieldShape(memory, fieldName) {
  const field = memory[fieldName];
  assert.ok(field !== undefined, `${fieldName} must not be undefined`);
  assert.equal(typeof field, "object", `${fieldName} must be an object`);
  assert.ok(field !== null, `${fieldName} must not be null`);
  assert.equal(typeof field.value, "string", `${fieldName}.value must be a string`);
  assert.ok(SOURCE_TAGS.has(field.source), `${fieldName}.source must be a known tag, got ${field.source}`);
}

function formatUnknown(field) {
  return `${field.value}, source: ${field.source}`;
}

test("generates summary for a project with README and git log, keeping missing SDD tagged", async () => {
  const generateProjectMemory = await loadMemory();
  const workspacePath = await createProjectWithReadmeAndGit();

  const memory = await generateProjectMemory(workspacePath);

  for (const fieldName of MEMORY_FIELDS) {
    assertFieldShape(memory, fieldName);
  }

  assert.match(memory.purpose.value, /fish inventory|Demo App/i);
  assert.equal(memory.purpose.source, "README");
  assert.notEqual(memory.git.value, "unknown");
  assert.equal(memory.git.source, "Git");
  assert.match(memory.readme.value, /README\.md$/i);
  assert.equal(memory.readme.source, "README");
  assert.equal(formatUnknown(memory.sdd), "unknown, source: none");
});

test("empty directory without README or git history surfaces unknown, source: none", async () => {
  const generateProjectMemory = await loadMemory();
  const workspacePath = await createTempDir("project-memory-empty-");
  await mkdir(workspacePath, { recursive: true });

  const memory = await generateProjectMemory(workspacePath);

  for (const fieldName of ["purpose", "git", "readme", "sdd", "deployment", "nextStep", "status"]) {
    assertFieldShape(memory, fieldName);
    assert.equal(formatUnknown(memory[fieldName]), "unknown, source: none");
  }

  const fabricatedHints = /lorem|placeholder|todo fill|generated by ai|example project/i;
  for (const fieldName of MEMORY_FIELDS) {
    assert.doesNotMatch(memory[fieldName].value, fabricatedHints);
  }
});

test("every returned Project Memory field includes a source tag", async () => {
  const generateProjectMemory = await loadMemory();
  const workspacePath = await createProjectWithReadmeAndGit();

  const memory = await generateProjectMemory(workspacePath);
  const keys = Object.keys(memory);

  assert.ok(keys.length >= MEMORY_FIELDS.length, "memory must return the required fields");
  for (const fieldName of keys) {
    assertFieldShape(memory, fieldName);
  }
  for (const fieldName of MEMORY_FIELDS) {
    assert.ok(Object.hasOwn(memory, fieldName), `missing required field ${fieldName}`);
  }
});
